### ISSUE TITLE
ERROR: current segment is 10249396 12586797, position is 1

### ISSUE THREAD

**Issue by guruprem** [joepickrell/gwas-pw#2]
Hi, 

Thanks for the GWAS-PW. 

I am facing this error for selected input files, where the currentseg.first and current.seg.second is varying along with the position.
I am not able to understand the problem here, as the files are sorted based on chromosome with no duplicates. Just pasting the head of one of the input file.

phenotype 1: VDM
phenotype 2: TG
VDM with TG
SNPID   CHR     POS     Z_VDM   V_VDM   Z_TG    V_TG
1:751756        chr1    751756  -0.769  0.00231709710327169     -0.91437075478898       0.013103
1:752566        chr1    752566  -1.079  0.00251099724456947     1.4500042988565 0.011631
1:752721        chr1    752721  1.108   0.00262025919987935     1.35041619063163        0.012254
1:752894        chr1    752894  0.952   0.00265428592420037     1.62889357560026        0.012328

The same phenotypes with other different combinations working fine. for instance.
WMH with VDM
TG with WMH

Any suggestions will be of great help.

Thanks
Murali

**Comment by corunesa85** [comment]
I have a similar problem. How have you do you to solve it?
Thank you!

**Comment by tshhhh** [comment]
I have a similar problem. How have you do you to solve it?
Thank you!

**Comment by corunesa** [comment]
I think my data was not right ordered. Are your sure your data are properly ordered?

**Comment by tshhhh** [comment]
Is the data arranged in the order of "POS" column？

**Comment by tshhhh** [comment]
How have you do you to solve it?

**Comment by corunesa** [comment]
It should be ordered by chromosome and then position, like this:
tbl<-tbl[order(as.numeric(as.factor(tbl$CHR)),as.numeric(tbl$POS)),]
where tbl is your data, CHR is the column chromosome and POS the column position

**Comment by tshhhh** [comment]
Thank you very much. I'll try your way.

**Comment by Steven-ZWQ** [comment]
ERROR: current segment is 70755198 73174848, position is 7
Dataset was ordered as suggested "tbl<-tbl[order(as.numeric(as.factor(tbl$CHR)),as.numeric(tbl$POS)),]"
How do you fix it?

**Comment by corunesa** [comment]
could you show us how is your file?
